"""Agent commerce SDK — identity middleware + payment helpers + 402 builders + discovery + Stripe multichain.

Submodules:
    agentscore_commerce.identity   - per-framework gate adapters
    agentscore_commerce.payment    - networks/usdc/rails registries, directives, x402/mpp helpers
    agentscore_commerce.discovery  - probe + .well-known/mpp.json + llms.txt + OpenAPI snippets
    agentscore_commerce.challenge  - 402-body builders
    agentscore_commerce.stripe_multichain - multichain PaymentIntent helpers
    agentscore_commerce.checkout   - high-level Checkout orchestrator
    agentscore_commerce.api        - AgentScore SDK re-export
"""

from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _pkg_version

from agentscore_commerce.checkout import (
    Checkout,
    CheckoutContext,
    CheckoutGateConfig,
    CheckoutRailSpec,
    CheckoutRequest,
    CheckoutResult,
    CheckoutValidationError,
    DiscoveryProbeConfig,
    MppxComposeOutcome,
    PricingResult,
    SettleOutcome,
    format_pydantic_errors,
    pricing_result,
    validation_envelope,
    validation_response_aiohttp,
    validation_response_django,
    validation_response_fastapi,
    validation_response_flask,
    validation_response_sanic,
)
from agentscore_commerce.checkout_compute_first import (
    ComputeFirstCheckout,
    ComputeFirstMintContext,
    ComputeFirstMppContext,
    ComputeFirstMppResult,
    ComputeFirstRails,
    ComputeFirstRequest,
    ComputeFirstSettledContext,
    ComputeFirstWorkContext,
    MintedRecipients,
    SuccessBodyArgs,
    WorkOutcome,
    compute_first_checkout,
)
from agentscore_commerce.checkout_hooks import make_mppx_compose_hook

# Re-export the most commonly used helpers at the package root so consumers
# don't have to remember which submodule each one lives in. Mirrors node's
# top-level `index.ts` surface; submodule imports still work for power users.
from agentscore_commerce.identity import (
    AGENTSCORE_UCP_CAPABILITY,
    FIXABLE_DENIAL_REASONS,
    UCP_A2A_EXTENSION_URI,
    A2AAgentCard,
    A2AAgentCardCapabilities,
    A2AAgentCardExtension,
    A2AAgentCardSignature,
    A2AAgentInterface,
    A2AAgentProvider,
    A2AAgentSkill,
    AgentIdentity,
    AgentMemoryHint,
    AgentScoreCore,
    AgentScoreGatePolicy,
    AssessResult,
    DefaultOnDeniedResult,
    DenialCode,
    DenialReason,
    EnforcementMode,
    GateResult,
    GeneratedUCPKey,
    IdentityStatus,
    OwnerScope,
    PolicyBlock,
    SignerVerdict,
    UCPCapabilityBinding,
    UCPPaymentHandlerBinding,
    UCPProfile,
    UCPProfileBody,
    UCPServiceBinding,
    UCPSigningKey,
    UCPVerificationError,
    VerifyWalletSignerResult,
    build_a2a_agent_card,
    build_agent_memory_hint,
    build_contact_support_next_steps,
    build_gate_from_policy,
    build_jwks_response,
    build_signer_mismatch_body,
    build_ucp_profile,
    create_default_on_denied,
    default_read_only_on_denied,
    denial_reason_status,
    denial_reason_to_body,
    extract_owner_scope,
    generate_ucp_signing_key,
    hash_operator_token,
    is_fixable_denial,
    load_ucp_signing_key_from_env,
    mpp_payment_handler,
    run_gate_with_enforcement,
    shipping_country_allowed,
    shipping_state_allowed,
    sign_ucp_profile,
    stripe_spt_payment_handler,
    ucp_a2a_extension,
    validate_shipping_against_policy,
    verification_agent_instructions,
    verify_ucp_profile,
    x402_payment_handler,
)
from agentscore_commerce.identity.sessions import CreateSessionOnMissing
from agentscore_commerce.identity.types import PolicyCheck, PolicyResult
from agentscore_commerce.payment import (
    PaymentSigner,
    SignerNetwork,
    SolanaMppRailSpec,
    StripeRailSpec,
    TempoRailSpec,
    TempoSessionRailSpec,
    X402BaseRailSpec,
    build_default_checkout_rails,
    build_mppx_compose_rails,
    extract_payment_signer,
    extract_signer_for_precheck,
    format_usd_cents,
    has_mppx_header,
    has_payment_header,
    has_x402_header,
    is_evm_network,
    is_solana_network,
    load_solana_fee_payer,
    read_x402_payment_header,
)
from agentscore_commerce.quote_cache import CachedQuote, QuoteCache, create_quote_cache

try:
    __version__ = _pkg_version("agentscore-commerce")
except PackageNotFoundError:
    # Editable install or pre-build state — fall back to a sentinel so consumers
    # don't crash on a missing dist-info dir. Real version always comes from
    # pyproject.toml at install time.
    __version__ = "0.0.0+local"

__all__ = [
    "AGENTSCORE_UCP_CAPABILITY",
    "FIXABLE_DENIAL_REASONS",
    "UCP_A2A_EXTENSION_URI",
    "A2AAgentCard",
    "A2AAgentCardCapabilities",
    "A2AAgentCardExtension",
    "A2AAgentCardSignature",
    "A2AAgentInterface",
    "A2AAgentProvider",
    "A2AAgentSkill",
    "AgentIdentity",
    "AgentMemoryHint",
    "AgentScoreCore",
    "AgentScoreGatePolicy",
    "AssessResult",
    "CachedQuote",
    "Checkout",
    "CheckoutContext",
    "CheckoutGateConfig",
    "CheckoutRailSpec",
    "CheckoutRequest",
    "CheckoutResult",
    "CheckoutValidationError",
    "ComputeFirstCheckout",
    "ComputeFirstMintContext",
    "ComputeFirstMppContext",
    "ComputeFirstMppResult",
    "ComputeFirstRails",
    "ComputeFirstRequest",
    "ComputeFirstSettledContext",
    "ComputeFirstWorkContext",
    "CreateSessionOnMissing",
    "DefaultOnDeniedResult",
    "DenialCode",
    "DenialReason",
    "DiscoveryProbeConfig",
    "EnforcementMode",
    "GateResult",
    "GeneratedUCPKey",
    "IdentityStatus",
    "MintedRecipients",
    "MppxComposeOutcome",
    "OwnerScope",
    "PaymentSigner",
    "PolicyBlock",
    "PolicyCheck",
    "PolicyResult",
    "PricingResult",
    "QuoteCache",
    "SettleOutcome",
    "SignerNetwork",
    "SignerVerdict",
    "SolanaMppRailSpec",
    "StripeRailSpec",
    "SuccessBodyArgs",
    "TempoRailSpec",
    "TempoSessionRailSpec",
    "UCPCapabilityBinding",
    "UCPPaymentHandlerBinding",
    "UCPProfile",
    "UCPProfileBody",
    "UCPServiceBinding",
    "UCPSigningKey",
    "UCPVerificationError",
    "VerifyWalletSignerResult",
    "WorkOutcome",
    "X402BaseRailSpec",
    "__version__",
    "build_a2a_agent_card",
    "build_agent_memory_hint",
    "build_contact_support_next_steps",
    "build_default_checkout_rails",
    "build_gate_from_policy",
    "build_jwks_response",
    "build_mppx_compose_rails",
    "build_signer_mismatch_body",
    "build_ucp_profile",
    "compute_first_checkout",
    "create_default_on_denied",
    "create_quote_cache",
    "default_read_only_on_denied",
    "denial_reason_status",
    "denial_reason_to_body",
    "extract_owner_scope",
    "extract_payment_signer",
    "extract_signer_for_precheck",
    "format_pydantic_errors",
    "format_usd_cents",
    "generate_ucp_signing_key",
    "has_mppx_header",
    "has_payment_header",
    "has_x402_header",
    "hash_operator_token",
    "is_evm_network",
    "is_fixable_denial",
    "is_solana_network",
    "load_solana_fee_payer",
    "load_ucp_signing_key_from_env",
    "make_mppx_compose_hook",
    "mpp_payment_handler",
    "pricing_result",
    "read_x402_payment_header",
    "run_gate_with_enforcement",
    "shipping_country_allowed",
    "shipping_state_allowed",
    "sign_ucp_profile",
    "stripe_spt_payment_handler",
    "ucp_a2a_extension",
    "validate_shipping_against_policy",
    "validation_envelope",
    "validation_response_aiohttp",
    "validation_response_django",
    "validation_response_fastapi",
    "validation_response_flask",
    "validation_response_sanic",
    "verification_agent_instructions",
    "verify_ucp_profile",
    "x402_payment_handler",
]
