"""Regenerate the full cross-lang fixture corpus (Python side).

Writes all ``py-*.json`` fixtures under ``tests/fixtures/cross-lang/``. Used after a
canonicalization-relevant change (typ rename, capability-name rename, schema-URL
rename, key-sort tweak, profile-shape change) where every JWS in the corpus needs
to be re-signed.

Each scenario hand-crafts the profile body using the spec-compliant input shape
(``services`` / ``capabilities`` / ``payment_handlers`` as MAPS keyed by reverse-DNS
service / capability / handler name), signs with a fresh keypair, and writes the
``{profile, jwks, alg, kid, generator}`` envelope. Cross-lang verify in
``tests/test_ucp_cross_lang.py`` (and the Node sibling) pulls these in alongside the
``node-*`` fixtures generated by the Node sibling.

Run: ``uv run python scripts/regenerate_cross_lang_fixtures.py``
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from agentscore_commerce.identity import (
    AssessResult,
    OperatorVerification,
    UCPCapabilityBinding,
    UCPPaymentHandlerBinding,
    UCPServiceBinding,
    UCPSigningKey,
    build_ucp_profile,
)
from agentscore_commerce.identity.ucp_jwks import (
    build_jwks_response,
    generate_ucp_signing_key,
    sign_ucp_profile,
)

OUT_DIR = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "cross-lang"


def _write(name: str, env: dict[str, Any]) -> None:
    out = OUT_DIR / f"{name}.json"
    out.write_text(json.dumps(env, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {out}")


def _envelope(signed: dict[str, Any], public_jwk: dict[str, Any], alg: str, kid: str) -> dict[str, Any]:
    return {
        "profile": signed,
        "jwks": build_jwks_response([public_jwk]),
        "alg": alg,
        "kid": kid,
        "generator": "python",
    }


# Spec-compliant binding helpers — each scenario uses these (or variants) so the
# fixtures cover the full set of canonical UCP fields per binding type.


def _shop_service_mcp(host: str) -> UCPServiceBinding:
    return UCPServiceBinding(
        version="2026-04-08",
        spec="https://ucp.dev/2026-04-08/specification/overview",
        transport="mcp",
        endpoint=f"{host}/api/ucp/mcp",
        schema="https://ucp.dev/services/shopping/openrpc.json",
    )


def _shop_service_a2a(host: str) -> UCPServiceBinding:
    return UCPServiceBinding(
        version="2026-04-08",
        spec="https://ucp.dev/2026-04-08/specification/overview",
        transport="a2a",
        endpoint=f"{host}/.well-known/agent-card.json",
    )


def _tempo_handler(config: dict[str, Any] | None = None) -> UCPPaymentHandlerBinding:
    h = UCPPaymentHandlerBinding(
        id="tempo",
        version="2026-04-08",
        spec="https://agentscore.sh/specification/payment-handlers/tempo",
        schema="https://agentscore.sh/schemas/payment-handlers/tempo.json",
    )
    if config is not None:
        h.config = config
    return h


def _x402_handler(networks: list[str]) -> UCPPaymentHandlerBinding:
    return UCPPaymentHandlerBinding(
        id="x402",
        version="2026-04-08",
        spec="https://agentscore.sh/specification/payment-handlers/x402",
        schema="https://agentscore.sh/schemas/payment-handlers/x402.json",
        config={"networks": networks},
    )


def _stripe_handler(config: dict[str, Any]) -> UCPPaymentHandlerBinding:
    return UCPPaymentHandlerBinding(
        id="stripe",
        version="2026-04-08",
        spec="https://agentscore.sh/specification/payment-handlers/stripe-spt",
        schema="https://agentscore.sh/schemas/payment-handlers/stripe-spt.json",
        config=config,
    )


def main() -> None:
    # py-minimal — empty maps; just metadata + signing keys.
    kid = "py-minimal-EdDSA"
    key = generate_ucp_signing_key(kid=kid)
    profile = build_ucp_profile(
        services={"dev.ucp.shopping": [_shop_service_mcp("https://m.example.com")]},
        signing_keys=[UCPSigningKey.from_jwk(key.public_jwk)],
        name="Minimal Merchant",
    )
    signed = sign_ucp_profile(profile.to_dict(), signing_key=key.private_key, kid=kid)
    _write("py-minimal", _envelope(signed, key.public_jwk, "EdDSA", kid))

    # py-es256-rails — multi-transport service + multi-rail + ES256 signing key.
    kid = "py-es256-rails-ES256"
    key = generate_ucp_signing_key(kid=kid, alg="ES256")
    profile = build_ucp_profile(
        services={
            "dev.ucp.shopping": [
                _shop_service_mcp("https://a.example.com"),
                _shop_service_a2a("https://a.example.com"),
            ],
        },
        signing_keys=[UCPSigningKey.from_jwk(key.public_jwk)],
        payment_handlers={
            "sh.agentscore.payment.tempo": [_tempo_handler({"rail": "tempo-mainnet", "chain_id": 4217})],
            "sh.agentscore.payment.x402": [_x402_handler(["base-8453"])],
        },
        name="ES256 Merchant",
    )
    signed = sign_ucp_profile(profile.to_dict(), signing_key=key.private_key, kid=kid, alg="ES256")
    _write("py-es256-rails", _envelope(signed, key.public_jwk, "ES256", kid))

    # py-extras-int — payment_handler config with int + string fields.
    kid = "py-extras-int-EdDSA"
    key = generate_ucp_signing_key(kid=kid)
    profile = build_ucp_profile(
        services={"dev.ucp.shopping": [_shop_service_mcp("https://e.example.com")]},
        signing_keys=[UCPSigningKey.from_jwk(key.public_jwk)],
        payment_handlers={
            "sh.agentscore.payment.stripe-spt": [_stripe_handler({"profile_id": "abc", "count": 7})],
        },
        name="Extras Merchant",
    )
    signed = sign_ucp_profile(profile.to_dict(), signing_key=key.private_key, kid=kid)
    _write("py-extras-int", _envelope(signed, key.public_jwk, "EdDSA", kid))

    # py-capability — hand-crafted vendor capability under sh.agentscore.identity.
    kid = "py-capability-EdDSA"
    key = generate_ucp_signing_key(kid=kid)
    custom_capability = UCPCapabilityBinding(
        version="1",
        spec="https://agentscore.sh/specification/identity",
        schema="https://agentscore.sh/schemas/ucp/sh-agentscore-identity-v1.json",
        # `extras` flat on the binding — kyc_required is a vendor field on this binding.
        extras={"kyc_required": True},
    )
    profile = build_ucp_profile(
        services={"dev.ucp.shopping": [_shop_service_mcp("https://c.example.com")]},
        signing_keys=[UCPSigningKey.from_jwk(key.public_jwk)],
        capabilities={"sh.agentscore.identity": [custom_capability]},
        payment_handlers={
            "sh.agentscore.payment.tempo": [_tempo_handler({"rail": "tempo-mainnet", "chain_id": 4217})],
        },
        name="Capability Merchant",
    )
    signed = sign_ucp_profile(profile.to_dict(), signing_key=key.private_key, kid=kid)
    _write("py-capability", _envelope(signed, key.public_jwk, "EdDSA", kid))

    # py-unicode — multi-byte UTF-8 in name / endpoint / config.
    kid = "py-unicode-EdDSA"
    key = generate_ucp_signing_key(kid=kid)
    profile = build_ucp_profile(
        services={"dev.ucp.shopping": [_shop_service_mcp("https://日本.example.com")]},
        signing_keys=[UCPSigningKey.from_jwk(key.public_jwk)],
        payment_handlers={
            "sh.agentscore.payment.tempo": [_tempo_handler({"note": "メモ"})],
        },
        name="Café 日本 🍷 Merchant",
    )
    signed = sign_ucp_profile(profile.to_dict(), signing_key=key.private_key, kid=kid)
    _write("py-unicode", _envelope(signed, key.public_jwk, "EdDSA", kid))

    # py-multikey — JWKS with two keys, signed by the newer one.
    old_key = generate_ucp_signing_key(kid="py-multikey-old")
    new_key = generate_ucp_signing_key(kid="py-multikey-new")
    profile = build_ucp_profile(
        services={"dev.ucp.shopping": [_shop_service_mcp("https://mk.example.com")]},
        signing_keys=[
            UCPSigningKey.from_jwk(old_key.public_jwk),
            UCPSigningKey.from_jwk(new_key.public_jwk),
        ],
        payment_handlers={
            "sh.agentscore.payment.tempo": [_tempo_handler({"rail": "tempo-mainnet"})],
        },
        name="Multi-Key Merchant",
    )
    signed = sign_ucp_profile(profile.to_dict(), signing_key=new_key.private_key, kid="py-multikey-new")
    _write(
        "py-multikey",
        {
            "profile": signed,
            "jwks": build_jwks_response([old_key.public_jwk, new_key.public_jwk]),
            "alg": "EdDSA",
            "kid": "py-multikey-new",
            "generator": "python",
        },
    )

    # py-emoji-keys — extras at top-level (outside the `ucp` envelope) with non-ASCII
    # object keys (BMP private use, CJK compatibility, supplementary plane).
    # Exercises codepoint-vs-UTF-16 sort.
    kid = "py-emoji-keys-EdDSA"
    key = generate_ucp_signing_key(kid=kid)
    profile = build_ucp_profile(
        services={"dev.ucp.shopping": [_shop_service_mcp("https://emoji.example.com")]},
        signing_keys=[UCPSigningKey.from_jwk(key.public_jwk)],
        payment_handlers={
            "sh.agentscore.payment.tempo": [_tempo_handler()],
        },
        name="Emoji Keys Merchant",
        extras={
            "a": 1,
            "豈": 2,
            "": 3,
            "🍷": 4,
        },
    )
    signed = sign_ucp_profile(profile.to_dict(), signing_key=key.private_key, kid=kid)
    _write("py-emoji-keys", _envelope(signed, key.public_jwk, "EdDSA", kid))

    # py-int-boundary — exercises Number.MAX_SAFE_INTEGER round-trip via top-level extras.
    kid = "py-int-boundary-EdDSA"
    key = generate_ucp_signing_key(kid=kid)
    profile = build_ucp_profile(
        services={"dev.ucp.shopping": [_shop_service_mcp("https://i.example.com")]},
        signing_keys=[UCPSigningKey.from_jwk(key.public_jwk)],
        name="Int Boundary Merchant",
        extras={
            "max_safe_int": 9007199254740991,
            "min_safe_int": -9007199254740991,
            "small_int": 42,
            "neg_small_int": -42,
            "zero": 0,
        },
    )
    signed = sign_ucp_profile(profile.to_dict(), signing_key=key.private_key, kid=kid)
    _write("py-int-boundary", _envelope(signed, key.public_jwk, "EdDSA", kid))

    # py-data-driven-claims — exercises build_ucp_profile data path with API-shape
    # "missing" sentinels (empty string + None). Both languages MUST emit identical
    # canonical bytes for this input.
    kid = "py-data-driven-claims-EdDSA"
    key = generate_ucp_signing_key(kid=kid)
    result = AssessResult(
        allow=True,
        resolved_operator="op_data_driven",
        verify_url="https://agentscore.sh/verify/op_data_driven",
        raw={
            "account_verification": {
                "kyc_level": "",
                "sanctions_clear": False,
                "age_bracket": None,
                "jurisdiction": None,
                "verified_at": None,
            },
        },
    )
    profile = build_ucp_profile(
        services={"dev.ucp.shopping": [_shop_service_mcp("https://d.example.com")]},
        signing_keys=[UCPSigningKey.from_jwk(key.public_jwk)],
        name="Data Driven Claims Merchant",
        data=result,
    )
    signed = sign_ucp_profile(profile.to_dict(), signing_key=key.private_key, kid=kid)
    _write("py-data-driven-claims", _envelope(signed, key.public_jwk, "EdDSA", kid))

    # py-typed-claims — exercises typed AssessResult fields (no raw fallback).
    # Cross-lang parity check for the typed-field-only call site.
    kid = "py-typed-claims-EdDSA"
    key = generate_ucp_signing_key(kid=kid)
    result = AssessResult(
        allow=True,
        resolved_operator="op_typed_claims",
        verify_url="https://agentscore.sh/verify/op_typed_claims",
        operator_verification=OperatorVerification(
            level="enhanced",
            operator_type="api",
            verified_at="2026-04-01T00:00:00Z",
        ),
        account_verification={
            "kyc_level": "enhanced",
            "sanctions_clear": True,
            "age_bracket": "21+",
            "jurisdiction": "US",
            "verified_at": "2026-04-01T00:00:00Z",
        },
        raw=None,
    )
    profile = build_ucp_profile(
        services={"dev.ucp.shopping": [_shop_service_mcp("https://t.example.com")]},
        signing_keys=[UCPSigningKey.from_jwk(key.public_jwk)],
        name="Typed Claims Merchant",
        data=result,
    )
    signed = sign_ucp_profile(profile.to_dict(), signing_key=key.private_key, kid=kid)
    _write("py-typed-claims", _envelope(signed, key.public_jwk, "EdDSA", kid))


if __name__ == "__main__":
    main()
