"""Regenerate the full cross-lang fixture corpus (Python side).

Writes all ``py-*.json`` fixtures under ``tests/fixtures/cross-lang/``. Used
after a canonicalization-relevant change (typ rename, capability-name rename,
schema-URL rename, key-sort tweak, etc.) where every JWS in the corpus needs
to be re-signed.

Each scenario hand-crafts the profile body, signs with a fresh keypair, and
writes the ``{profile, jwks, alg, kid, generator}`` envelope. Cross-lang
verify in ``tests/test_ucp_cross_lang.py`` (and the Node sibling) pulls these
in alongside the ``node-*`` fixtures generated by the Node sibling.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from agentscore_commerce.identity import (
    AssessResult,
    OperatorVerification,
    UCPCapability,
    UCPPaymentHandler,
    UCPService,
    UCPSigningKey,
    build_ucp_profile,
)
from agentscore_commerce.identity.ucp_jwks import (
    build_jwks_response,
    generate_ucp_signing_key,
    sign_ucp_profile,
)

OUT_DIR = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "cross-lang"


def _write(name: str, env: dict[str, Any]) -> None:
    out = OUT_DIR / f"{name}.json"
    out.write_text(json.dumps(env, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {out}")


def _envelope(signed: dict[str, Any], public_jwk: dict[str, Any], alg: str, kid: str) -> dict[str, Any]:
    return {
        "profile": signed,
        "jwks": build_jwks_response([public_jwk]),
        "alg": alg,
        "kid": kid,
        "generator": "python",
    }


def main() -> None:
    # py-minimal
    kid = "py-minimal-EdDSA"
    key = generate_ucp_signing_key(kid=kid)
    profile = build_ucp_profile(
        name="Minimal Merchant",
        services=[UCPService(type="rest", url="https://m.example.com")],
        payment_handlers=[],
        signing_keys=[UCPSigningKey.from_jwk(key.public_jwk)],
    )
    signed = sign_ucp_profile(profile.to_dict(), signing_key=key.private_key, kid=kid)
    _write("py-minimal", _envelope(signed, key.public_jwk, "EdDSA", kid))

    # py-es256-rails
    kid = "py-es256-rails-ES256"
    key = generate_ucp_signing_key(kid=kid, alg="ES256")
    profile = build_ucp_profile(
        name="ES256 Merchant",
        services=[
            UCPService(type="rest", url="https://a.example.com"),
            UCPService(type="a2a", url="https://a.example.com/agent-card.json"),
        ],
        payment_handlers=[
            UCPPaymentHandler(name="tempo", config={"rail": "tempo-mainnet", "chain_id": 4217}),
            UCPPaymentHandler(name="x402", config={"networks": ["base-8453"]}),
        ],
        signing_keys=[UCPSigningKey.from_jwk(key.public_jwk)],
    )
    signed = sign_ucp_profile(profile.to_dict(), signing_key=key.private_key, kid=kid, alg="ES256")
    _write("py-es256-rails", _envelope(signed, key.public_jwk, "ES256", kid))

    # py-extras-int
    kid = "py-extras-int-EdDSA"
    key = generate_ucp_signing_key(kid=kid)
    profile = build_ucp_profile(
        name="Extras Merchant",
        services=[UCPService(type="rest", url="https://e.example.com")],
        payment_handlers=[UCPPaymentHandler(name="stripe", config={"profile_id": "abc", "count": 7})],
        signing_keys=[UCPSigningKey.from_jwk(key.public_jwk)],
    )
    signed = sign_ucp_profile(profile.to_dict(), signing_key=key.private_key, kid=kid)
    _write("py-extras-int", _envelope(signed, key.public_jwk, "EdDSA", kid))

    # py-capability — hand-crafted vendor capability (renamed to
    # sh.agentscore.identity to match the new namespace; the in-fixture name
    # is independent of the SDK's auto-injection but consistency keeps the
    # corpus honest about what callers should publish).
    kid = "py-capability-EdDSA"
    key = generate_ucp_signing_key(kid=kid)
    profile = build_ucp_profile(
        name="Capability Merchant",
        services=[UCPService(type="rest", url="https://c.example.com")],
        capabilities=[
            UCPCapability(
                name="sh.agentscore.identity",
                schema="https://agentscore.sh/schemas/ucp/sh-agentscore-identity-v1.json",
                version="1",
                extras={"kyc_required": True},
            ),
        ],
        payment_handlers=[
            UCPPaymentHandler(name="tempo", config={"rail": "tempo-mainnet", "chain_id": 4217}),
        ],
        signing_keys=[UCPSigningKey.from_jwk(key.public_jwk)],
    )
    signed = sign_ucp_profile(profile.to_dict(), signing_key=key.private_key, kid=kid)
    _write("py-capability", _envelope(signed, key.public_jwk, "EdDSA", kid))

    # py-unicode
    kid = "py-unicode-EdDSA"
    key = generate_ucp_signing_key(kid=kid)
    profile = build_ucp_profile(
        name="Café 日本 🍷 Merchant",
        services=[UCPService(type="rest", url="https://日本.example.com")],
        payment_handlers=[UCPPaymentHandler(name="tempo", config={"note": "メモ"})],
        signing_keys=[UCPSigningKey.from_jwk(key.public_jwk)],
    )
    signed = sign_ucp_profile(profile.to_dict(), signing_key=key.private_key, kid=kid)
    _write("py-unicode", _envelope(signed, key.public_jwk, "EdDSA", kid))

    # py-multikey — JWKS with two keys, signed by the newer one.
    old_key = generate_ucp_signing_key(kid="py-multikey-old")
    new_key = generate_ucp_signing_key(kid="py-multikey-new")
    profile = build_ucp_profile(
        name="Multi-Key Merchant",
        services=[UCPService(type="rest", url="https://mk.example.com")],
        payment_handlers=[UCPPaymentHandler(name="tempo", config={"rail": "tempo-mainnet"})],
        signing_keys=[
            UCPSigningKey.from_jwk(old_key.public_jwk),
            UCPSigningKey.from_jwk(new_key.public_jwk),
        ],
    )
    signed = sign_ucp_profile(profile.to_dict(), signing_key=new_key.private_key, kid="py-multikey-new")
    _write(
        "py-multikey",
        {
            "profile": signed,
            "jwks": build_jwks_response([old_key.public_jwk, new_key.public_jwk]),
            "alg": "EdDSA",
            "kid": "py-multikey-new",
            "generator": "python",
        },
    )

    # py-emoji-keys — extras with non-ASCII object keys (BMP private use, CJK
    # compatibility, supplementary plane). Exercises codepoint-vs-UTF-16 sort.
    kid = "py-emoji-keys-EdDSA"
    key = generate_ucp_signing_key(kid=kid)
    profile = build_ucp_profile(
        name="Emoji Keys Merchant",
        services=[UCPService(type="rest", url="https://emoji.example.com")],
        payment_handlers=[UCPPaymentHandler(name="tempo", config={})],
        signing_keys=[UCPSigningKey.from_jwk(key.public_jwk)],
        extras={
            "a": 1,
            "豈": 2,
            "": 3,
            "🍷": 4,
        },
    )
    signed = sign_ucp_profile(profile.to_dict(), signing_key=key.private_key, kid=kid)
    _write("py-emoji-keys", _envelope(signed, key.public_jwk, "EdDSA", kid))

    # py-int-boundary — exercises Number.MAX_SAFE_INTEGER round-trip.
    kid = "py-int-boundary-EdDSA"
    key = generate_ucp_signing_key(kid=kid)
    profile = build_ucp_profile(
        name="Int Boundary Merchant",
        services=[UCPService(type="rest", url="https://i.example.com")],
        payment_handlers=[],
        signing_keys=[UCPSigningKey.from_jwk(key.public_jwk)],
        extras={
            "max_safe_int": 9007199254740991,
            "min_safe_int": -9007199254740991,
            "small_int": 42,
            "neg_small_int": -42,
            "zero": 0,
        },
    )
    signed = sign_ucp_profile(profile.to_dict(), signing_key=key.private_key, kid=kid)
    _write("py-int-boundary", _envelope(signed, key.public_jwk, "EdDSA", kid))

    # py-data-driven-claims — exercises the build_ucp_profile data path with
    # API-shape "missing" sentinels (empty string + None). Both languages MUST
    # emit identical canonical bytes for this input.
    kid = "py-data-driven-claims-EdDSA"
    key = generate_ucp_signing_key(kid=kid)
    result = AssessResult(
        allow=True,
        resolved_operator="op_data_driven",
        verify_url="https://agentscore.sh/verify/op_data_driven",
        raw={
            "account_verification": {
                "kyc_level": "",
                "sanctions_clear": False,
                "age_bracket": None,
                "jurisdiction": None,
                "verified_at": None,
            },
        },
    )
    profile = build_ucp_profile(
        name="Data Driven Claims Merchant",
        services=[UCPService(type="rest", url="https://d.example.com")],
        payment_handlers=[],
        signing_keys=[UCPSigningKey.from_jwk(key.public_jwk)],
        data=result,
    )
    signed = sign_ucp_profile(profile.to_dict(), signing_key=key.private_key, kid=kid)
    _write("py-data-driven-claims", _envelope(signed, key.public_jwk, "EdDSA", kid))

    # py-typed-claims — exercises the typed AssessResult fields (no raw
    # fallback). Cross-lang parity check for the typed-field-only call site.
    kid = "py-typed-claims-EdDSA"
    key = generate_ucp_signing_key(kid=kid)
    result = AssessResult(
        allow=True,
        resolved_operator="op_typed_claims",
        verify_url="https://agentscore.sh/verify/op_typed_claims",
        operator_verification=OperatorVerification(
            level="enhanced",
            operator_type="api",
            verified_at="2026-04-01T00:00:00Z",
        ),
        account_verification={
            "kyc_level": "enhanced",
            "sanctions_clear": True,
            "age_bracket": "21+",
            "jurisdiction": "US",
            "verified_at": "2026-04-01T00:00:00Z",
        },
        raw=None,
    )
    profile = build_ucp_profile(
        name="Typed Claims Merchant",
        services=[UCPService(type="rest", url="https://t.example.com")],
        payment_handlers=[],
        signing_keys=[UCPSigningKey.from_jwk(key.public_jwk)],
        data=result,
    )
    signed = sign_ucp_profile(profile.to_dict(), signing_key=key.private_key, kid=kid)
    _write("py-typed-claims", _envelope(signed, key.public_jwk, "EdDSA", kid))


if __name__ == "__main__":
    main()
